kind: pipeline
name: OSQ

steps:
- name: PIO
  image: python:3
  commands:
  - apt update
  - apt install -y git
  - git submodule update --init --recursive
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - pio platform install https://github.com/OS-Q/P122/archive/pio.zip
  - pio run -d examples/native-blink
