version: 2
jobs:

  QIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install platformio
            pio platform install https://github.com/OS-Q/P14/archive/pio.zip
      - run:
          name: "Build"
          command: |
            pio run -d examples/native-blink
            pio run -d examples/stc-blink
            pio run -d examples/stc-header

  PIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/platformio/platformio/archive/develop.zip
            pio platform install https://github.com/OS-Q/P14/archive/pio.zip
      - run:
          name: "Build"
          command: |
            pio run -d examples/native-blink
            pio run -d examples/stc-blink
            pio run -d examples/stc-header

workflows:
    version: 2
    run_ci:
        jobs:
          - QIO
          - PIO
